
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'About StoryForge',
    description: 'Learn more about StoryForge, an interactive storytelling platform powered by AI.',
};

export default function AboutPage() {
  return (
    <section id="about" className="w-full py-16 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="max-w-3xl mx-auto text-center">
          <h1 className="text-3xl font-headline font-bold tracking-tighter sm:text-5xl">
            What is StoryForge?
          </h1>
          <p className="mt-4 text-muted-foreground md:text-lg">
            It's an interactive storytelling platform where you are the author. Start with a simple prompt and watch as our AI co-writer helps you build a unique world, one choice at a time. Explore infinite possibilities and see where your imagination takes you.
          </p>
          <p className="mt-4 text-muted-foreground md:text-lg">
            StoryForge is built with a modern tech stack including Next.js, React, TypeScript, and Tailwind CSS. The AI-powered narrative is generated by Google's Gemini models through Genkit, creating dynamic and ever-evolving stories based on your choices.
          </p>
        </div>
      </div>
    </section>
  );
}
