
"use client";

import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { useStory } from "@/lib/story-context";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { ArrowRight, BookCopy, PenSquare, GitMerge, Star, Users, Download, BotMessageSquare } from "lucide-react";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";

export default function Home() {
  const { stories } = useStory();
  const heroImage = PlaceHolderImages.find(img => img.id === "hero-background");
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  const communityStats = [
    { name: "Stories Created", value: isClient ? stories.length : 0, icon: BookCopy },
    { name: "Community Stars", value: "1.2k", icon: Star },
    { name: "Active Contributors", value: "24", icon: Users },
    { name: "AI Invocations", value: "10k+", icon: BotMessageSquare },
  ];

  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
  };

  return (
    <div className="flex flex-col min-h-screen">
      {/* Hero Section */}
      <section className="relative w-full py-20 md:py-32 lg:py-40 flex items-center justify-center text-center">
        {heroImage && (
          <Image
            src={heroImage.imageUrl}
            alt={heroImage.description}
            fill
            className="object-cover"
            data-ai-hint={heroImage.imageHint}
            priority
          />
        )}
        <div className="absolute inset-0 bg-background/70 backdrop-blur-sm" />
        <div className="container relative px-4 md:px-6">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl font-headline font-bold tracking-tighter text-foreground sm:text-5xl md:text-6xl">
              StoryForge
            </h1>
            <p className="mt-4 text-foreground/90 md:text-xl">
              Craft your own adventure. Every choice carves a new path in an ever-evolving story, generated by AI.
            </p>
            <div className="mt-8 flex flex-wrap gap-4 justify-center">
              <Button size="lg" asChild>
                <Link href="/create">
                  <PenSquare className="mr-2 h-5 w-5" />
                  Create a New Story
                </Link>
              </Button>
              <Button size="lg" variant="secondary" asChild>
                <Link href="#about">
                  Learn More <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="w-full py-16 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl font-headline font-bold tracking-tighter sm:text-4xl">What is StoryForge?</h2>
            <p className="mt-4 text-muted-foreground md:text-lg">
              It's an interactive storytelling platform where you are the author. Start with a simple prompt and watch as our AI co-writer helps you build a unique world, one choice at a time. Explore infinite possibilities and see where your imagination takes you.
            </p>
          </div>
        </div>
      </section>

      {/* Story Library Section */}
      <section className="w-full py-16 md:py-24 lg:py-32 bg-secondary/50">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-headline font-bold tracking-tighter sm:text-5xl">Your Story Library</h2>
              {isClient && (
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  {stories.length > 0 ? "Continue your adventures or start a new one." : "Your created stories will appear here. Let's create your first!"}
                </p>
              )}
            </div>
          </div>
          {isClient && stories.length > 0 ? (
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-8 py-12 sm:grid-cols-2 lg:grid-cols-3">
              {stories.slice(0, 3).map((story, i) => (
                <motion.div
                  key={story.id}
                  variants={cardVariants}
                  initial="hidden"
                  whileInView="visible"
                  viewport={{ once: true, amount: 0.3 }}
                  transition={{ delay: i * 0.1 }}
                >
                  <Card className="h-full flex flex-col group overflow-hidden transition-all duration-300 ease-in-out hover:shadow-xl hover:shadow-primary/10 hover:border-primary/30 hover:-translate-y-1 bg-card/80 backdrop-blur-sm">
                    <CardHeader>
                      <CardTitle className="font-headline flex items-center gap-2">
                        <BookCopy className="w-5 h-5 text-primary" />
                        {story.title}
                      </CardTitle>
                      <CardDescription>Genre: {story.genre}</CardDescription>
                    </CardHeader>
                    <CardContent className="flex-grow flex flex-col justify-between">
                      <p className="text-sm text-muted-foreground mb-4">
                        {Object.keys(story.nodes).length} parts explored.
                      </p>
                      <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                        <Button asChild variant="outline" size="sm" className="w-full sm:w-auto sm:px-4 md:w-full">
                          <Link href={`/story/${story.id}`}>
                            Continue Story <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                          </Link>
                        </Button>
                      </motion.div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          ) : isClient ? (
             <div className="text-center py-12">
               <p className="text-muted-foreground">No stories yet. Time to create one!</p>
               <Button asChild className="mt-4">
                  <Link href="/create">
                    <PenSquare className="mr-2 h-5 w-5" />
                    Start Your First Story
                  </Link>
                </Button>
            </div>
          ) : null}
        </div>
      </section>

      {/* Community Section */}
      <section className="w-full py-16 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-headline font-bold tracking-tighter sm:text-5xl">Join the Community</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed">
                This project is open-source and built with the help of creators like you.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl grid-cols-2 gap-4 py-12 sm:grid-cols-4">
            {communityStats.map((stat) => (
              <div key={stat.name} className="flex flex-col items-center justify-center gap-2 p-4 rounded-lg bg-secondary/50">
                <stat.icon className="w-8 h-8 text-primary" />
                <p className="text-2xl font-bold">{stat.value}</p>
                <p className="text-sm text-muted-foreground text-center">{stat.name}</p>
              </div>
            ))}
          </div>
          <div className="text-center">
            <Button asChild size="lg">
              <a href="https://github.com/your-repo" target="_blank" rel="noopener noreferrer">
                <GitMerge className="mr-2 h-5 w-5" />
                Contribute on GitHub
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="w-full py-8 bg-secondary/50 mt-auto">
        <div className="container px-4 md:px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-sm text-muted-foreground">
            &copy; {new Date().getFullYear()} StoryForge. All rights reserved.
          </p>
          <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary font-medium">
            <Download className="w-4 h-4" />
            <p className="text-sm">Mobile apps coming soon!</p>
          </div>
           <div className="flex gap-4">
              <a href="#" className="text-muted-foreground hover:text-foreground">Twitter</a>
              <a href="#" className="text-muted-foreground hover:text-foreground">Discord</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
