import Image from "next/image";
import {Button} from "@/components/ui/button";
import Link from "next/link";
import {ArrowRight, PenSquare} from "lucide-react";
import {PlaceHolderImages} from "@/lib/placeholder-images";

const Hero =()=>{
    const heroImage = PlaceHolderImages.find(img => img.id === "hero-background");
    const handleScrollToAbout = () => {
        const aboutSection = document.getElementById("about");
        if (aboutSection) {
            aboutSection.scrollIntoView({ behavior: "smooth" });
        }
    };
    return(
        <section className="relative w-full h-[calc(100vh-3.5rem)] flex items-center justify-center text-center text-white">
            {heroImage && (
                <Image
                    src={heroImage.imageUrl}
                    alt={heroImage.description}
                    fill
                    className="object-cover"
                    data-ai-hint={heroImage.imageHint}
                    priority
                />
            )}
            <div className="absolute inset-0 bg-black/50" />
            <div className="container relative px-4 md:px-6">
                <div className="max-w-3xl mx-auto">
                    <h1 className="text-4xl font-headline font-bold tracking-tighter sm:text-5xl md:text-6xl">
                        FlowTale+
                    </h1>
                    <p className="mt-4 md:text-xl">
                        Craft your own adventure. Every choice carves a new path in an ever-evolving story, generated by AI.
                    </p>
                    <div className="mt-8 flex flex-wrap gap-4 justify-center">
                        <Button size="lg" asChild>
                            <Link href="/create">
                                <PenSquare className="mr-2 h-5 w-5" />
                                Create a New Story
                            </Link>
                        </Button>
                        <Link href={"#about"}>
                            <Button size="lg" variant="secondary" >
                                Learn More <ArrowRight className="ml-2 h-5 w-5" />
                            </Button>
                        </Link>
                    </div>
                </div>
            </div>
        </section>
    )
}
export default Hero